/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salesInvoiceGenerator.view;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import salesInvoiceGenerator.model.Invoice;
import salesInvoiceGenerator.model.InvoiceItems;
import salseInvoiceGenerator.controller.ActionHandler;

/**
 *
 * @author pc
 */
public class InvoiceFram extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceFram
     */
    public InvoiceFram() {
        actionHandler = new ActionHandler(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoiceLable = new javax.swing.JLabel();
        createInvoiceButton = new javax.swing.JButton();

        deleteInvoiceButton = new javax.swing.JButton();
        deleteInvoiceButton.addActionListener(actionHandler);
        numberLable = new javax.swing.JLabel();
        dateLable = new javax.swing.JLabel();
        customerLable = new javax.swing.JLabel();
        totalLable = new javax.swing.JLabel();
        invoicesItemsLable = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        saveButton.addActionListener(actionHandler);
        cancelButton = new javax.swing.JButton();
        cancelButton.addActionListener(actionHandler);
        jScrollPane1 = new javax.swing.JScrollPane();
        invoicesTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        invoicesItemsTable = new javax.swing.JTable();
        numberResultsLable = new javax.swing.JLabel();
        totalResultsLable = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dateTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerTextPane = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadMenuItem = new javax.swing.JMenuItem();
        loadMenuItem.addActionListener(actionHandler);
        saveMenuItem = new javax.swing.JMenuItem();
        saveMenuItem.addActionListener(actionHandler);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoiceLable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        invoiceLable.setText("Invoices Table");

        createInvoiceButton.setText("Create New Invoice");
        createInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createInvoiceButtonActionPerformed(evt);
            }
        });

        deleteInvoiceButton.setText("Delete Invoice");
        deleteInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInvoiceButtonActionPerformed(evt);
            }
        });

        numberLable.setText("Invoice Number");
        numberLable.setAlignmentX(0.5F);

        dateLable.setText("Invoice Date");

        customerLable.setText("Customer Name");
        customerLable.setMaximumSize(new java.awt.Dimension(62, 16));
        customerLable.setMinimumSize(new java.awt.Dimension(62, 16));
        customerLable.setPreferredSize(new java.awt.Dimension(62, 16));

        totalLable.setText("Invoice Total");

        invoicesItemsLable.setText("Invoices Items Table");
        invoicesItemsLable.setToolTipText("");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        invoicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "22-11-2021", "Ali", null},
                { new Integer(2), "13-10-2021", "Salah", null}
            },
            new String [] {
                "No.", "Date", "Customer", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        invoicesTable.setShowGrid(true);
        invoicesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoicesTableMouseClicked(evt);
            }
        });
        invoicesTable.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                invoicesTableVetoableChange(evt);
            }
        });
        jScrollPane1.setViewportView(invoicesTable);

        invoicesItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Mobile",  new Double(3200.0),  new Integer(1), null},
                { new Integer(1), "Cover",  new Double(20.0),  new Integer(2), null},
                { new Integer(1), "Headphone",  new Double(130.0),  new Integer(1), null}
            },
            new String [] {
                "No.", "Item Name", "Item Price", "Count", "Item Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        invoicesItemsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        invoicesItemsTable.setShowGrid(true);
        invoicesItemsTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                invoicesItemsTableComponentAdded(evt);
            }
        });
        jScrollPane6.setViewportView(invoicesItemsTable);

        jScrollPane2.setViewportView(dateTextPane);

        jScrollPane3.setViewportView(customerTextPane);

        fileMenu.setText("File");

        loadMenuItem.setText("Load File");
        loadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadMenuItem);

        saveMenuItem.setText("Save File");
        fileMenu.add(saveMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(invoicesItemsLable, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(customerLable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(dateLable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(numberLable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalLable, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numberResultsLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalResultsLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(invoiceLable, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(createInvoiceButton)
                .addGap(51, 51, 51)
                .addComponent(deleteInvoiceButton)
                .addGap(143, 143, 143)
                .addComponent(saveButton)
                .addGap(68, 68, 68)
                .addComponent(cancelButton)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(invoiceLable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberLable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberResultsLable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customerLable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalResultsLable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(invoicesItemsLable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteInvoiceButton)
                    .addComponent(createInvoiceButton)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createInvoiceButtonActionPerformed
        
        DefaultTableModel itemsTableModel = (DefaultTableModel) invoicesItemsTable.getModel();

        Invoice incoviceNumber = (Invoice) itemsTableModel.getValueAt(0, 0);
        String itemName = (String) itemsTableModel.getValueAt(0, 1);
        double itemPrice = (double) itemsTableModel.getValueAt(0, 2);
        int count = (int) itemsTableModel.getValueAt(0, 3);

        InvoiceItems item = new InvoiceItems(incoviceNumber, itemName, itemPrice, count);

        itemsTableModel.setValueAt(item.getItemTotal(), 0, 4);
        
    }//GEN-LAST:event_createInvoiceButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInvoiceButtonActionPerformed
        DefaultTableModel invoiceTableModel = (DefaultTableModel) invoicesTable.getModel();
        invoiceTableModel.removeRow(invoicesTable.getSelectedRow());
        numberResultsLable.setText("");
        dateTextPane.setText("");
        customerTextPane.setText("");
        totalResultsLable.setText("");

    }//GEN-LAST:event_deleteInvoiceButtonActionPerformed

    private void loadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMenuItemActionPerformed
       JFileChooser fileChooser = new JFileChooser();
        int results = fileChooser.showOpenDialog(this);
        if (results == JFileChooser.APPROVE_OPTION) {
            File firstSelectedFile = fileChooser.getSelectedFile();
            FileReader firstFile;
            try {
                // For First File
                firstFile = new FileReader(firstSelectedFile);
                BufferedReader firstFileBr = new BufferedReader(firstFile);
                String firstFileLine;
                firstFileLine = firstFileBr.readLine();
                String[] invoicesColumns = firstFileLine.split(",");

                DefaultTableModel invoicesTableModel = (DefaultTableModel) invoicesTable.getModel();
                invoicesTableModel.setColumnIdentifiers(invoicesColumns);
                Object[] invoicesTableRows = firstFileBr.lines().toArray();
                for (Object invoicesTableRow : invoicesTableRows) {
                    String invoiceRow = invoicesTableRow.toString();
                    String[] invoiceData = invoiceRow.split(",");
                    invoicesTableModel.addRow(invoiceData);
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(InvoiceFram.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(InvoiceFram.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        JFileChooser itemfileChooser = new JFileChooser();
        results = itemfileChooser.showOpenDialog(this);
        if (results == JFileChooser.APPROVE_OPTION) {
            File selectedFile = itemfileChooser.getSelectedFile();

            FileReader file;

            try {
                file = new FileReader(selectedFile);
                BufferedReader fileBr = new BufferedReader(file);
                String fileLine;
                fileLine = fileBr.readLine();
                String[] itemsColumns = fileLine.split(",");

                DefaultTableModel itemsTableModel = (DefaultTableModel) invoicesItemsTable.getModel();
                itemsTableModel.setColumnIdentifiers(itemsColumns);
                Object[] itemsTableRows = fileBr.lines().toArray();
                for (Object itemsTableRow : itemsTableRows) {
                    String invoiceRow = itemsTableRow.toString();
                    String[] itemsData = invoiceRow.split(",");
                    itemsTableModel.addRow(itemsData);
                }

            } catch (FileNotFoundException ex) {
                Logger.getLogger(InvoiceFram.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(InvoiceFram.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_loadMenuItemActionPerformed

    private void invoicesTableVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_invoicesTableVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_invoicesTableVetoableChange

    private void invoicesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoicesTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel invoiceModel = (DefaultTableModel) invoicesTable.getModel();
        int selectedRow = invoicesTable.getSelectedRow();
        numberResultsLable.setText(invoiceModel.getValueAt(selectedRow, 0).toString());
        dateTextPane.setText(invoiceModel.getValueAt(selectedRow, 1).toString());
        customerTextPane.setText(invoiceModel.getValueAt(selectedRow, 2).toString());
        totalResultsLable.setText(invoiceModel.getValueAt(selectedRow, 3).toString());

        // invoicesItemsTable.getModel().getValueAt(rowIndex, columnIndex);

    }//GEN-LAST:event_invoicesTableMouseClicked

    private void invoicesItemsTableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_invoicesItemsTableComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_invoicesItemsTableComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createInvoiceButton;
    private javax.swing.JLabel customerLable;
    private javax.swing.JTextPane customerTextPane;
    private javax.swing.JLabel dateLable;
    private javax.swing.JTextPane dateTextPane;
    private javax.swing.JButton deleteInvoiceButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel invoiceLable;
    private javax.swing.JLabel invoicesItemsLable;
    private javax.swing.JTable invoicesItemsTable;
    private javax.swing.JTable invoicesTable;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JLabel numberLable;
    private javax.swing.JLabel numberResultsLable;
    private javax.swing.JButton saveButton;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel totalLable;
    private javax.swing.JLabel totalResultsLable;
    // End of variables declaration//GEN-END:variables

    
    private ActionHandler actionHandler; 

}
